name: gplx_600_cau
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  collection: ^1.18.0
  sqflite: ^2.3.2
  get_it: ^7.7.0
  flutter_easyloading: ^3.0.5
  injectable: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.1.4
  flutter_bloc: ^8.1.5
  dio: ^5.4.1
  equatable: ^2.0.5
  path: ^1.9.0
  dartz: ^0.10.1
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.1
  go_router_builder: ^2.4.1
  freezed: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/database/gplx.db
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

flutter_gen: